name: springapp

# ワークフローをいつ実行するかを制御
on:
  # プッシュリクエストイベントでメインブランチに対してワークフローをトリガーする
  push:
    branches: [ master ]
    tags:
      - 'v*'
    
  #[アクション]タブからこのワークフローを手動で実行できる
  workflow_dispatch:

jobs:
  build:
    # ジョブが実行されるランナーのタイプ実行環境
    runs-on: ubuntu-latest

    # ステップは、ジョブの一部として実行される一連のタスクを表す
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v2
      
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
            java-version: '16'

      - name: Maven purge
        run: mvn dependency:purge-local-repository -DreResolve=false -f src/main/webapp/META-INF/maven/kakeibo/kakeibo/pom.xml

      - name: Build and Test with Maven
        run: mvn clean package -f src/main/webapp/META-INF/maven/kakeibo/kakeibo/pom.xml



      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: n148/springapp


       # DockerHub ログイン
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKRHUB_USERNAME }}
          password: ${{ secrets.DOCKRHUB_TOKEN }}

      # BuildKitの有効化
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
       
      # コンテナビルド＆格納
      - name: Build and push 
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
 
